// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://omrrlhxdfycihncmbyit.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9tcnJsaHhkZnljaWhuY21ieWl0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1MzI4NzcsImV4cCI6MjA2MTEwODg3N30.4dGMtjzLDyyMibRyZ9YtL63ge28JYcy-4IKI1BHVZn8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);